//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public Animal()
        {
            this.UserFarms = new HashSet<UserFarm>();
            this.UserFarmHistories = new HashSet<UserFarmHistory>();
        }
    
        public int Id { get; set; }
        public string Breed { get; set; }
        public string Varieties { get; set; }
        public string Rarity { get; set; }
        public string Weight { get; set; }
        public string Class { get; set; }
        public string Origins { get; set; }
        public string EggsColor { get; set; }
        public string EggSize { get; set; }
        public string Comb { get; set; }
        public string SkinColor { get; set; }
        public string Earlobes { get; set; }
        public string Brooding { get; set; }
        public string Hardiness { get; set; }
        public string Maturing { get; set; }
        public string Behavior { get; set; }
        public string Picture { get; set; }
        public string Links { get; set; }
        public Nullable<double> EggCost { get; set; }
        public Nullable<int> EggHatchingDays { get; set; }
    
        public virtual ICollection<UserFarm> UserFarms { get; set; }
        public virtual ICollection<UserFarmHistory> UserFarmHistories { get; set; }
    }
}
