//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetShopsWorkingHour
    {
        public int Id { get; set; }
        public string MondayStartTime { get; set; }
        public string MondayEndTime { get; set; }
        public string TuesdayStartTime { get; set; }
        public string WednesdayStartTime { get; set; }
        public string ThursdayStartTime { get; set; }
        public string FridayStartTime { get; set; }
        public string SaturdayStartTime { get; set; }
        public string SundayStartTime { get; set; }
        public string TuesdayEndTime { get; set; }
        public string WednesdayEndTime { get; set; }
        public string ThursdayEndTime { get; set; }
        public string FridayEndTime { get; set; }
        public string SaturdayEndTime { get; set; }
        public string SundayEndTime { get; set; }
    }
}
