//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class BirdVet
    {
        public int Id { get; set; }
        public string Zip { get; set; }
        public string Name { get; set; }
        public string ClinicName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    }
}
