//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempZipCode
    {
        public string Zip { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Country { get; set; }
        public Nullable<bool> Parsed { get; set; }
    }
}
