//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYFarmerConsoleServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public Asset()
        {
            this.UserAssets = new HashSet<UserAsset>();
            this.UserAssetsHistories = new HashSet<UserAssetsHistory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<double> Cost { get; set; }
        public int AddedByUser { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<UserAsset> UserAssets { get; set; }
        public virtual ICollection<UserAssetsHistory> UserAssetsHistories { get; set; }
    }
}
