//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYFarmerConsoleServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetShop
    {
        public int Id { get; set; }
        public string Zip { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string MonStart { get; set; }
        public string MonEnd { get; set; }
        public string TueStart { get; set; }
        public string TueEnd { get; set; }
        public string WedStart { get; set; }
        public string WedEnd { get; set; }
        public string ThuStart { get; set; }
        public string ThuEnd { get; set; }
        public string FriStart { get; set; }
        public string FriEnd { get; set; }
        public string SatStart { get; set; }
        public string SatEnd { get; set; }
        public string SunStart { get; set; }
        public string SunEnd { get; set; }
    }
}
