//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetVetsDoctorsInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChickenLaw
    {
        public int Id { get; set; }
        public string Location { get; set; }
        public string AreChickensAllowed { get; set; }
        public string ChickensAllowed { get; set; }
        public string RoostersAllowed { get; set; }
        public string PermitRequired { get; set; }
        public string CoopRestrictions { get; set; }
        public string Contacts { get; set; }
        public string Info { get; set; }
        public string Link { get; set; }
        public string LastUpdate { get; set; }
    }
}
