//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetVetsDoctorsInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTraining
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int TrainingId { get; set; }
        public System.DateTime DateCompleted { get; set; }
    
        public virtual Training Training { get; set; }
        public virtual User User { get; set; }
    }
}
