//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetVets
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class keydowno_backyard_farmerEntities : DbContext
    {
        public keydowno_backyard_farmerEntities()
            : base("name=keydowno_backyard_farmerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BirdVets> BirdVets { get; set; }
        public DbSet<ChickenLaws> ChickenLaws { get; set; }
        public DbSet<PetShops> PetShops { get; set; }
        public DbSet<PetShopsWorkingHours> PetShopsWorkingHours { get; set; }
        public DbSet<TempZipCodes> TempZipCodes { get; set; }
        public DbSet<Vets> Vets { get; set; }
        public DbSet<VetsWorkingHours> VetsWorkingHours { get; set; }
        public DbSet<ZipCode> ZipCode { get; set; }
    }
}
