//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetVets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vets
    {
        public int Id { get; set; }
        public string Zip { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string Image { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    
        public virtual VetsWorkingHours VetsWorkingHours { get; set; }
    }
}
